
const mockRooms = [
    {
        _id: "69a54021638eda22b11c436b",
        name: "Oceanview Suite",
        description: "Spacious suite with stunning ocean views and modern decor.",
        images: [
            "/images/oceanview_suite1.jpg",
            "/images/oceanview_suite2.jpg",
        ],
        price: 220,
        rating: 4.8,
        ratingCount: 128,
        maxGuests: 3,
        amenities: ["wifi", "ac", "tv", "coffee"],
        view: "ocean",
        roomType: "suite",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c436c",
        name: "City Loft",
        description: "Modern loft-style room in the heart of downtown with skyline views.",
        images: [
            "/images/city_loft_room1.jpg",
            "/images/city_loft_room2.jpg",
        ],
        price: 150,
        rating: 4.3,
        ratingCount: 76,
        maxGuests: 2,
        amenities: ["wifi", "ac", "tv"],
        view: "city",
        roomType: "double",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c436d",
        name: "Garden Room",
        description: "Cozy room overlooking a lush garden for a peaceful stay.",
        images: [
            "/images/garden_view1.jpg",
            "/images/garden_view2.jpg",
        ],
        price: 120,
        rating: 4.0,
        ratingCount: 54,
        maxGuests: 2,
        amenities: ["wifi", "ac"],
        view: "garden",
        roomType: "single",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c436e",
        name: "Mountain Cabin",
        description: "Rustic yet comfortable cabin-style room with mountain views.",
        images: [
            "/images/mountain_cabin1.jpg",
            "/images/mountain_cabin2.jpg",
        ],
        price: 180,
        rating: 4.6,
        ratingCount: 89,
        maxGuests: 4,
        amenities: ["wifi", "tv", "coffee"],
        view: "mountain",
        roomType: "suite",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c436f",
        name: "Historic Deluxe",
        description: "Classic luxury room in a historic building with antique furnishings.",
        images: [
            "/images/historic_deluxe1.jpg",
            "/images/historic_deluxe2.jpg",
        ],
        price: 200,
        rating: 4.9,
        ratingCount: 210,
        maxGuests: 2,
        amenities: ["wifi", "ac", "tv", "coffee"],
        view: "city",
        roomType: "double",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c4370",
        name: "Oceanview Suite 6",
        description: "Spacious suite with stunning ocean views and modern decor.",
        images: [
            "/images/oceanview_suite1.jpg",
            "/images/oceanview_suite2.jpg",
        ],
        price: 220,
        rating: 4.8,
        ratingCount: 128,
        maxGuests: 3,
        amenities: ["wifi", "ac", "tv", "coffee"],
        view: "ocean",
        roomType: "suite",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c4371",
        name: "City Loft 7",
        description: "Modern loft-style room in the heart of downtown with skyline views.",
        images: [
            "/images/city_loft_room1.jpg",
            "/images/city_loft_room2.jpg",
        ],
        price: 150,
        rating: 4.3,
        ratingCount: 76,
        maxGuests: 2,
        amenities: ["wifi", "ac", "tv"],
        view: "city",
        roomType: "double",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c4372",
        name: "Garden Room 8",
        description: "Cozy room overlooking a lush garden for a peaceful stay.",
        images: [
            "/images/garden_view1.jpg",
            "/images/garden_view2.jpg",
        ],
        price: 120,
        rating: 4.0,
        ratingCount: 54,
        maxGuests: 2,
        amenities: ["wifi", "ac"],
        view: "garden",
        roomType: "single",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c4373",
        name: "Mountain Cabin 9",
        description: "Rustic yet comfortable cabin-style room with mountain views.",
        images: [
            "/images/mountain_cabin1.jpg",
            "/images/mountain_cabin2.jpg",
        ],
        price: 180,
        rating: 4.6,
        ratingCount: 89,
        maxGuests: 4,
        amenities: ["wifi", "tv", "coffee"],
        view: "mountain",
        roomType: "suite",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c4374",
        name: "Historic Deluxe 10",
        description: "Classic luxury room in a historic building with antique furnishings.",
        images: [
            "/images/historic_deluxe1.jpg",
            "/images/historic_deluxe2.jpg",
        ],
        price: 200,
        rating: 4.9,
        ratingCount: 210,
        maxGuests: 2,
        amenities: ["wifi", "ac", "tv", "coffee"],
        view: "city",
        roomType: "double",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c4375",
        name: "Oceanview Suite 11",
        description: "Spacious suite with stunning ocean views and modern decor.",
        images: [
            "/images/oceanview_suite1.jpg",
            "/images/oceanview_suite2.jpg",
        ],
        price: 220,
        rating: 4.8,
        ratingCount: 128,
        maxGuests: 3,
        amenities: ["wifi", "ac", "tv", "coffee"],
        view: "ocean",
        roomType: "suite",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c4376",
        name: "City Loft 12",
        description: "Modern loft-style room in the heart of downtown with skyline views.",
        images: [
            "/images/city_loft_room1.jpg",
            "/images/city_loft_room2.jpg",
        ],
        price: 150,
        rating: 4.3,
        ratingCount: 76,
        maxGuests: 2,
        amenities: ["wifi", "ac", "tv"],
        view: "city",
        roomType: "double",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c4377",
        name: "Garden Room 13",
        description: "Cozy room overlooking a lush garden for a peaceful stay.",
        images: [
            "/images/garden_view1.jpg",
            "/images/garden_view2.jpg",
        ],
        price: 120,
        rating: 4.0,
        ratingCount: 54,
        maxGuests: 2,
        amenities: ["wifi", "ac"],
        view: "garden",
        roomType: "single",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c4378",
        name: "Mountain Cabin 14",
        description: "Rustic yet comfortable cabin-style room with mountain views.",
        images: [
            "/images/mountain_cabin1.jpg",
            "/images/mountain_cabin2.jpg",
        ],
        price: 180,
        rating: 4.6,
        ratingCount: 89,
        maxGuests: 4,
        amenities: ["wifi", "tv", "coffee"],
        view: "mountain",
        roomType: "suite",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c4379",
        name: "Historic Deluxe 15",
        description: "Classic luxury room in a historic building with antique furnishings.",
        images: [
            "/images/historic_deluxe1.jpg",
            "/images/historic_deluxe2.jpg",
        ],
        price: 200,
        rating: 4.9,
        ratingCount: 210,
        maxGuests: 2,
        amenities: ["wifi", "ac", "tv", "coffee"],
        view: "city",
        roomType: "double",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c437a",
        name: "Oceanview Suite 16",
        description: "Spacious suite with stunning ocean views and modern decor.",
        images: [
            "/images/oceanview_suite1.jpg",
            "/images/oceanview_suite2.jpg",
        ],
        price: 220,
        rating: 4.8,
        ratingCount: 128,
        maxGuests: 3,
        amenities: ["wifi", "ac", "tv", "coffee"],
        view: "ocean",
        roomType: "suite",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c437b",
        name: "City Loft 17",
        description: "Modern loft-style room in the heart of downtown with skyline views.",
        images: [
            "/images/city_loft_room1.jpg",
            "/images/city_loft_room2.jpg",
        ],
        price: 150,
        rating: 4.3,
        ratingCount: 76,
        maxGuests: 2,
        amenities: ["wifi", "ac", "tv"],
        view: "city",
        roomType: "double",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c437c",
        name: "Garden Room 18",
        description: "Cozy room overlooking a lush garden for a peaceful stay.",
        images: [
            "/images/garden_view1.jpg",
            "/images/garden_view2.jpg",
        ],
        price: 120,
        rating: 4.0,
        ratingCount: 54,
        maxGuests: 2,
        amenities: ["wifi", "ac"],
        view: "garden",
        roomType: "single",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c437d",
        name: "Mountain Cabin 19",
        description: "Rustic yet comfortable cabin-style room with mountain views.",
        images: [
            "/images/mountain_cabin1.jpg",
            "/images/mountain_cabin2.jpg",
        ],
        price: 180,
        rating: 4.6,
        ratingCount: 89,
        maxGuests: 4,
        amenities: ["wifi", "tv", "coffee"],
        view: "mountain",
        roomType: "suite",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c437e",
        name: "Historic Deluxe 20",
        description: "Classic luxury room in a historic building with antique furnishings.",
        images: [
            "/images/historic_deluxe1.jpg",
            "/images/historic_deluxe2.jpg",
        ],
        price: 200,
        rating: 4.9,
        ratingCount: 210,
        maxGuests: 2,
        amenities: ["wifi", "ac", "tv", "coffee"],
        view: "city",
        roomType: "double",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c437f",
        name: "Oceanview Suite 21",
        description: "Spacious suite with stunning ocean views and modern decor.",
        images: [
            "/images/oceanview_suite1.jpg",
            "/images/oceanview_suite2.jpg",
        ],
        price: 220,
        rating: 4.8,
        ratingCount: 128,
        maxGuests: 3,
        amenities: ["wifi", "ac", "tv", "coffee"],
        view: "ocean",
        roomType: "suite",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c4380",
        name: "City Loft 22",
        description: "Modern loft-style room in the heart of downtown with skyline views.",
        images: [
            "/images/city_loft_room1.jpg",
            "/images/city_loft_room2.jpg",
        ],
        price: 150,
        rating: 4.3,
        ratingCount: 76,
        maxGuests: 2,
        amenities: ["wifi", "ac", "tv"],
        view: "city",
        roomType: "double",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c4381",
        name: "Garden Room 23",
        description: "Cozy room overlooking a lush garden for a peaceful stay.",
        images: [
            "/images/garden_view1.jpg",
            "/images/garden_view2.jpg",
        ],
        price: 120,
        rating: 4.0,
        ratingCount: 54,
        maxGuests: 2,
        amenities: ["wifi", "ac"],
        view: "garden",
        roomType: "single",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c4382",
        name: "Mountain Cabin 24",
        description: "Rustic yet comfortable cabin-style room with mountain views.",
        images: [
            "/images/mountain_cabin1.jpg",
            "/images/mountain_cabin2.jpg",
        ],
        price: 180,
        rating: 4.6,
        ratingCount: 89,
        maxGuests: 4,
        amenities: ["wifi", "tv", "coffee"],
        view: "mountain",
        roomType: "suite",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c4383",
        name: "Historic Deluxe 25",
        description: "Classic luxury room in a historic building with antique furnishings.",
        images: [
            "/images/historic_deluxe1.jpg",
            "/images/historic_deluxe2.jpg",
        ],
        price: 200,
        rating: 4.9,
        ratingCount: 210,
        maxGuests: 2,
        amenities: ["wifi", "ac", "tv", "coffee"],
        view: "city",
        roomType: "double",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c4384",
        name: "Oceanview Suite 26",
        description: "Spacious suite with stunning ocean views and modern decor.",
        images: [
            "/images/oceanview_suite1.jpg",
            "/images/oceanview_suite2.jpg",
        ],
        price: 220,
        rating: 4.8,
        ratingCount: 128,
        maxGuests: 3,
        amenities: ["wifi", "ac", "tv", "coffee"],
        view: "ocean",
        roomType: "suite",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c4385",
        name: "City Loft 27",
        description: "Modern loft-style room in the heart of downtown with skyline views.",
        images: [
            "/images/city_loft_room1.jpg",
            "/images/city_loft_room2.jpg",
        ],
        price: 150,
        rating: 4.3,
        ratingCount: 76,
        maxGuests: 2,
        amenities: ["wifi", "ac", "tv"],
        view: "city",
        roomType: "double",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c4386",
        name: "Garden Room 28",
        description: "Cozy room overlooking a lush garden for a peaceful stay.",
        images: [
            "/images/garden_view1.jpg",
            "/images/garden_view2.jpg",
        ],
        price: 120,
        rating: 4.0,
        ratingCount: 54,
        maxGuests: 2,
        amenities: ["wifi", "ac"],
        view: "garden",
        roomType: "single",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c4387",
        name: "Mountain Cabin 29",
        description: "Rustic yet comfortable cabin-style room with mountain views.",
        images: [
            "/images/mountain_cabin1.jpg",
            "/images/mountain_cabin2.jpg",
        ],
        price: 180,
        rating: 4.6,
        ratingCount: 89,
        maxGuests: 4,
        amenities: ["wifi", "tv", "coffee"],
        view: "mountain",
        roomType: "suite",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c4388",
        name: "Historic Deluxe 30",
        description: "Classic luxury room in a historic building with antique furnishings.",
        images: [
            "/images/historic_deluxe1.jpg",
            "/images/historic_deluxe2.jpg",
        ],
        price: 200,
        rating: 4.9,
        ratingCount: 210,
        maxGuests: 2,
        amenities: ["wifi", "ac", "tv", "coffee"],
        view: "city",
        roomType: "double",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c4389",
        name: "Oceanview Suite 31",
        description: "Spacious suite with stunning ocean views and modern decor.",
        images: [
            "/images/oceanview_suite1.jpg",
            "/images/oceanview_suite2.jpg",
        ],
        price: 220,
        rating: 4.8,
        ratingCount: 128,
        maxGuests: 3,
        amenities: ["wifi", "ac", "tv", "coffee"],
        view: "ocean",
        roomType: "suite",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c438a",
        name: "City Loft 32",
        description: "Modern loft-style room in the heart of downtown with skyline views.",
        images: [
            "/images/city_loft_room1.jpg",
            "/images/city_loft_room2.jpg",
        ],
        price: 150,
        rating: 4.3,
        ratingCount: 76,
        maxGuests: 2,
        amenities: ["wifi", "ac", "tv"],
        view: "city",
        roomType: "double",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c438b",
        name: "Garden Room 33",
        description: "Cozy room overlooking a lush garden for a peaceful stay.",
        images: [
            "/images/garden_view1.jpg",
            "/images/garden_view2.jpg",
        ],
        price: 120,
        rating: 4.0,
        ratingCount: 54,
        maxGuests: 2,
        amenities: ["wifi", "ac"],
        view: "garden",
        roomType: "single",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c438c",
        name: "Mountain Cabin 34",
        description: "Rustic yet comfortable cabin-style room with mountain views.",
        images: [
            "/images/mountain_cabin1.jpg",
            "/images/mountain_cabin2.jpg",
        ],
        price: 180,
        rating: 4.6,
        ratingCount: 89,
        maxGuests: 4,
        amenities: ["wifi", "tv", "coffee"],
        view: "mountain",
        roomType: "suite",
        
        totalRooms: 5,
        availableRooms: 5,
    },
    {
        _id: "69a54021638eda22b11c438d",
        name: "Historic Deluxe 35",
        description: "Classic luxury room in a historic building with antique furnishings.",
        images: [
            "/images/historic_deluxe1.jpg",
            "/images/historic_deluxe2.jpg",
        ],
        price: 200,
        rating: 4.9,
        ratingCount: 210,
        maxGuests: 2,
        amenities: ["wifi", "ac", "tv", "coffee"],
        view: "city",
        roomType: "double",
        
        totalRooms: 5,
        availableRooms: 5,
    }
];

export default mockRooms;